2023-10-18 16:04:21,524 - speechbrain.core - INFO - Beginning experiment!
2023-10-18 16:04:21,524 - speechbrain.core - INFO - Experiment folder: Results/Ultrasound_sinc
2023-10-18 16:04:21,831 - speechbrain.utils.superpowers - DEBUG - appdirs==1.4.4
audioread==3.0.0
beautifulsoup4==4.12.2
bs4==0.0.1
certifi @ file:///croot/certifi_1690232220950/work/certifi
cffi==1.15.1
charset-normalizer==3.2.0
cloudpickle==2.2.1
cmake==3.27.5
contourpy==1.1.1
cssselect==1.2.0
cycler==0.11.0
Cython==3.0.2
decorator==5.1.1
dnspython==2.4.2
exceptiongroup==1.1.3
fake-useragent==1.2.1
falcon==3.1.1
falcon-cors==1.1.7
filelock==3.12.4
fonttools==4.42.1
fsspec==2023.9.2
gitdb==4.0.10
GitPython==3.1.36
GPy==1.10.0
gunicorn==21.2.0
huggingface-hub==0.17.3
HyperPyYAML==1.2.2
idna==3.4
importlib-metadata==6.8.0
iniconfig==2.0.0
Jinja2==3.1.2
joblib==1.3.2
kaleido==0.2.1
kiwisolver==1.4.5
lazy_loader==0.3
librosa==0.10.1
lit==16.0.6
llvmlite==0.41.0
lxml==4.9.3
MarkupSafe==2.1.3
matplotlib==3.8.0
mpmath==1.3.0
msgpack==1.0.6
networkx==3.1
numba==0.58.0
numpy==1.25.2
nvidia-cublas-cu11==11.10.3.66
nvidia-cuda-cupti-cu11==11.7.101
nvidia-cuda-nvrtc-cu11==11.7.99
nvidia-cuda-runtime-cu11==11.7.99
nvidia-cudnn-cu11==8.5.0.96
nvidia-cufft-cu11==10.9.0.58
nvidia-curand-cu11==10.2.10.91
nvidia-cusolver-cu11==11.4.0.1
nvidia-cusparse-cu11==11.7.4.91
nvidia-nccl-cu11==2.14.3
nvidia-nvtx-cu11==11.7.91
orion==0.2.7
packaging==23.1
pandas==2.1.1
paramz==0.9.5
parse==1.19.1
Pillow==10.0.1
platformdirs==3.10.0
plotly==5.17.0
pluggy==1.3.0
pooch==1.7.0
profet==0.0.1
psutil==5.9.5
pyaml==23.9.6
pycparser==2.21
pyee==8.2.2
pymongo==4.5.0
pyparsing==3.1.1
pypdb==2.3
pyppeteer==1.0.2
pyquery==2.0.0
pytest==7.4.2
python-dateutil==2.8.2
pytz==2023.3.post1
PyYAML==6.0.1
requests==2.31.0
requests-html==0.10.0
ruamel.yaml==0.17.35
ruamel.yaml.clib==0.2.8
scikit-learn==1.3.1
scikit-optimize==0.9.0
scipy==1.11.2
seaborn==0.12.2
sentencepiece==0.1.99
six==1.16.0
smmap==5.0.1
soundfile==0.12.1
soupsieve==2.5
soxr==0.3.6
speechbrain==0.5.15
sympy==1.12
tabulate==0.9.0
tenacity==8.2.3
threadpoolctl==3.2.0
tomli==2.0.1
torch==2.0.1
torchaudio==2.0.2
torchvision==0.15.2
tqdm==4.66.1
triton==2.0.0
typing_extensions==4.8.0
tzdata==2023.3
urllib3==1.26.16
w3lib==2.1.2
websockets==10.4
zipp==3.17.0


2023-10-18 16:04:21,833 - speechbrain.utils.superpowers - DEBUG - 188471c


2023-10-18 16:04:22,961 - speechbrain.core - INFO - 176.2k trainable parameters in Ultra_Brain
2023-10-18 16:04:22,962 - speechbrain.utils.checkpoints - INFO - Would load a checkpoint here, but none found yet.
2023-10-18 16:04:22,962 - speechbrain.utils.epoch_loop - INFO - Going into epoch 1
2023-10-18 16:04:22,969 - speechbrain.core - ERROR - Exception:
Traceback (most recent call last):
  File "/home/arian/PycharmProjects/SpeechBrain_Ultra/./models/train_NeuralNets_sinc.py", line 155, in <module>
    Ultra_brain.fit(
  File "/home/arian/anaconda3/envs/StableV4/lib/python3.10/site-packages/speechbrain/core.py", line 1264, in fit
    self._fit_train(train_set=train_set, epoch=epoch, enable=enable)
  File "/home/arian/anaconda3/envs/StableV4/lib/python3.10/site-packages/speechbrain/core.py", line 1116, in _fit_train
    loss = self.fit_batch(batch)
  File "/home/arian/PycharmProjects/SpeechBrain_Ultra/./models/train_NeuralNets_sinc.py", line 51, in fit_batch
    predictions = self.compute_forward(batch)
  File "/home/arian/PycharmProjects/SpeechBrain_Ultra/./models/train_NeuralNets_sinc.py", line 37, in compute_forward
    a = self.modules.CnnBlock(rf)
  File "/home/arian/anaconda3/envs/StableV4/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/arian/anaconda3/envs/StableV4/lib/python3.10/site-packages/torch/nn/modules/container.py", line 217, in forward
    input = module(input)
  File "/home/arian/anaconda3/envs/StableV4/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/arian/anaconda3/envs/StableV4/lib/python3.10/site-packages/speechbrain/nnet/CNN.py", line 148, in forward
    raise ValueError(
ValueError: Padding must be 'same', 'valid' or 'causal'. Got 1.
2023-10-18 16:04:49,915 - speechbrain.core - INFO - Beginning experiment!
2023-10-18 16:04:49,915 - speechbrain.core - INFO - Experiment folder: Results/Ultrasound_sinc
2023-10-18 16:04:50,221 - speechbrain.utils.superpowers - DEBUG - appdirs==1.4.4
audioread==3.0.0
beautifulsoup4==4.12.2
bs4==0.0.1
certifi @ file:///croot/certifi_1690232220950/work/certifi
cffi==1.15.1
charset-normalizer==3.2.0
cloudpickle==2.2.1
cmake==3.27.5
contourpy==1.1.1
cssselect==1.2.0
cycler==0.11.0
Cython==3.0.2
decorator==5.1.1
dnspython==2.4.2
exceptiongroup==1.1.3
fake-useragent==1.2.1
falcon==3.1.1
falcon-cors==1.1.7
filelock==3.12.4
fonttools==4.42.1
fsspec==2023.9.2
gitdb==4.0.10
GitPython==3.1.36
GPy==1.10.0
gunicorn==21.2.0
huggingface-hub==0.17.3
HyperPyYAML==1.2.2
idna==3.4
importlib-metadata==6.8.0
iniconfig==2.0.0
Jinja2==3.1.2
joblib==1.3.2
kaleido==0.2.1
kiwisolver==1.4.5
lazy_loader==0.3
librosa==0.10.1
lit==16.0.6
llvmlite==0.41.0
lxml==4.9.3
MarkupSafe==2.1.3
matplotlib==3.8.0
mpmath==1.3.0
msgpack==1.0.6
networkx==3.1
numba==0.58.0
numpy==1.25.2
nvidia-cublas-cu11==11.10.3.66
nvidia-cuda-cupti-cu11==11.7.101
nvidia-cuda-nvrtc-cu11==11.7.99
nvidia-cuda-runtime-cu11==11.7.99
nvidia-cudnn-cu11==8.5.0.96
nvidia-cufft-cu11==10.9.0.58
nvidia-curand-cu11==10.2.10.91
nvidia-cusolver-cu11==11.4.0.1
nvidia-cusparse-cu11==11.7.4.91
nvidia-nccl-cu11==2.14.3
nvidia-nvtx-cu11==11.7.91
orion==0.2.7
packaging==23.1
pandas==2.1.1
paramz==0.9.5
parse==1.19.1
Pillow==10.0.1
platformdirs==3.10.0
plotly==5.17.0
pluggy==1.3.0
pooch==1.7.0
profet==0.0.1
psutil==5.9.5
pyaml==23.9.6
pycparser==2.21
pyee==8.2.2
pymongo==4.5.0
pyparsing==3.1.1
pypdb==2.3
pyppeteer==1.0.2
pyquery==2.0.0
pytest==7.4.2
python-dateutil==2.8.2
pytz==2023.3.post1
PyYAML==6.0.1
requests==2.31.0
requests-html==0.10.0
ruamel.yaml==0.17.35
ruamel.yaml.clib==0.2.8
scikit-learn==1.3.1
scikit-optimize==0.9.0
scipy==1.11.2
seaborn==0.12.2
sentencepiece==0.1.99
six==1.16.0
smmap==5.0.1
soundfile==0.12.1
soupsieve==2.5
soxr==0.3.6
speechbrain==0.5.15
sympy==1.12
tabulate==0.9.0
tenacity==8.2.3
threadpoolctl==3.2.0
tomli==2.0.1
torch==2.0.1
torchaudio==2.0.2
torchvision==0.15.2
tqdm==4.66.1
triton==2.0.0
typing_extensions==4.8.0
tzdata==2023.3
urllib3==1.26.16
w3lib==2.1.2
websockets==10.4
zipp==3.17.0


2023-10-18 16:04:50,223 - speechbrain.utils.superpowers - DEBUG - 188471c


2023-10-18 16:04:51,301 - speechbrain.core - INFO - 176.2k trainable parameters in Ultra_Brain
2023-10-18 16:04:51,302 - speechbrain.utils.checkpoints - INFO - Would load a checkpoint here, but none found yet.
2023-10-18 16:04:51,302 - speechbrain.utils.epoch_loop - INFO - Going into epoch 1
2023-10-18 16:04:51,316 - speechbrain.core - ERROR - Exception:
Traceback (most recent call last):
  File "/home/arian/PycharmProjects/SpeechBrain_Ultra/./models/train_NeuralNets_sinc.py", line 155, in <module>
    Ultra_brain.fit(
  File "/home/arian/anaconda3/envs/StableV4/lib/python3.10/site-packages/speechbrain/core.py", line 1264, in fit
    self._fit_train(train_set=train_set, epoch=epoch, enable=enable)
  File "/home/arian/anaconda3/envs/StableV4/lib/python3.10/site-packages/speechbrain/core.py", line 1116, in _fit_train
    loss = self.fit_batch(batch)
  File "/home/arian/PycharmProjects/SpeechBrain_Ultra/./models/train_NeuralNets_sinc.py", line 51, in fit_batch
    predictions = self.compute_forward(batch)
  File "/home/arian/PycharmProjects/SpeechBrain_Ultra/./models/train_NeuralNets_sinc.py", line 37, in compute_forward
    a = self.modules.CnnBlock(rf)
  File "/home/arian/anaconda3/envs/StableV4/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/arian/anaconda3/envs/StableV4/lib/python3.10/site-packages/torch/nn/modules/container.py", line 217, in forward
    input = module(input)
  File "/home/arian/anaconda3/envs/StableV4/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/arian/anaconda3/envs/StableV4/lib/python3.10/site-packages/speechbrain/nnet/CNN.py", line 136, in forward
    x = self._manage_padding(
  File "/home/arian/anaconda3/envs/StableV4/lib/python3.10/site-packages/speechbrain/nnet/CNN.py", line 304, in _manage_padding
    x = F.pad(x, padding, mode=self.padding_mode)
RuntimeError: Argument #4: Padding size should be less than the corresponding input dimension, but got: padding (128, 128) at dimension 2 of input [6, 4500, 1]
2023-10-18 16:09:11,299 - speechbrain.core - INFO - Beginning experiment!
2023-10-18 16:09:11,300 - speechbrain.core - INFO - Experiment folder: Results/Ultrasound_sinc
2023-10-18 16:09:11,603 - speechbrain.utils.superpowers - DEBUG - appdirs==1.4.4
audioread==3.0.0
beautifulsoup4==4.12.2
bs4==0.0.1
certifi @ file:///croot/certifi_1690232220950/work/certifi
cffi==1.15.1
charset-normalizer==3.2.0
cloudpickle==2.2.1
cmake==3.27.5
contourpy==1.1.1
cssselect==1.2.0
cycler==0.11.0
Cython==3.0.2
decorator==5.1.1
dnspython==2.4.2
exceptiongroup==1.1.3
fake-useragent==1.2.1
falcon==3.1.1
falcon-cors==1.1.7
filelock==3.12.4
fonttools==4.42.1
fsspec==2023.9.2
gitdb==4.0.10
GitPython==3.1.36
GPy==1.10.0
gunicorn==21.2.0
huggingface-hub==0.17.3
HyperPyYAML==1.2.2
idna==3.4
importlib-metadata==6.8.0
iniconfig==2.0.0
Jinja2==3.1.2
joblib==1.3.2
kaleido==0.2.1
kiwisolver==1.4.5
lazy_loader==0.3
librosa==0.10.1
lit==16.0.6
llvmlite==0.41.0
lxml==4.9.3
MarkupSafe==2.1.3
matplotlib==3.8.0
mpmath==1.3.0
msgpack==1.0.6
networkx==3.1
numba==0.58.0
numpy==1.25.2
nvidia-cublas-cu11==11.10.3.66
nvidia-cuda-cupti-cu11==11.7.101
nvidia-cuda-nvrtc-cu11==11.7.99
nvidia-cuda-runtime-cu11==11.7.99
nvidia-cudnn-cu11==8.5.0.96
nvidia-cufft-cu11==10.9.0.58
nvidia-curand-cu11==10.2.10.91
nvidia-cusolver-cu11==11.4.0.1
nvidia-cusparse-cu11==11.7.4.91
nvidia-nccl-cu11==2.14.3
nvidia-nvtx-cu11==11.7.91
orion==0.2.7
packaging==23.1
pandas==2.1.1
paramz==0.9.5
parse==1.19.1
Pillow==10.0.1
platformdirs==3.10.0
plotly==5.17.0
pluggy==1.3.0
pooch==1.7.0
profet==0.0.1
psutil==5.9.5
pyaml==23.9.6
pycparser==2.21
pyee==8.2.2
pymongo==4.5.0
pyparsing==3.1.1
pypdb==2.3
pyppeteer==1.0.2
pyquery==2.0.0
pytest==7.4.2
python-dateutil==2.8.2
pytz==2023.3.post1
PyYAML==6.0.1
requests==2.31.0
requests-html==0.10.0
ruamel.yaml==0.17.35
ruamel.yaml.clib==0.2.8
scikit-learn==1.3.1
scikit-optimize==0.9.0
scipy==1.11.2
seaborn==0.12.2
sentencepiece==0.1.99
six==1.16.0
smmap==5.0.1
soundfile==0.12.1
soupsieve==2.5
soxr==0.3.6
speechbrain==0.5.15
sympy==1.12
tabulate==0.9.0
tenacity==8.2.3
threadpoolctl==3.2.0
tomli==2.0.1
torch==2.0.1
torchaudio==2.0.2
torchvision==0.15.2
tqdm==4.66.1
triton==2.0.0
typing_extensions==4.8.0
tzdata==2023.3
urllib3==1.26.16
w3lib==2.1.2
websockets==10.4
zipp==3.17.0


2023-10-18 16:09:11,605 - speechbrain.utils.superpowers - DEBUG - 188471c


2023-10-18 16:09:12,673 - speechbrain.core - INFO - 176.2k trainable parameters in Ultra_Brain
2023-10-18 16:09:12,674 - speechbrain.utils.checkpoints - INFO - Would load a checkpoint here, but none found yet.
2023-10-18 16:09:12,674 - speechbrain.utils.epoch_loop - INFO - Going into epoch 1
2023-10-18 16:09:12,686 - speechbrain.core - ERROR - Exception:
Traceback (most recent call last):
  File "/home/arian/PycharmProjects/SpeechBrain_Ultra/./models/train_NeuralNets_sinc.py", line 155, in <module>
    Ultra_brain.fit(
  File "/home/arian/anaconda3/envs/StableV4/lib/python3.10/site-packages/speechbrain/core.py", line 1264, in fit
    self._fit_train(train_set=train_set, epoch=epoch, enable=enable)
  File "/home/arian/anaconda3/envs/StableV4/lib/python3.10/site-packages/speechbrain/core.py", line 1116, in _fit_train
    loss = self.fit_batch(batch)
  File "/home/arian/PycharmProjects/SpeechBrain_Ultra/./models/train_NeuralNets_sinc.py", line 51, in fit_batch
    predictions = self.compute_forward(batch)
  File "/home/arian/PycharmProjects/SpeechBrain_Ultra/./models/train_NeuralNets_sinc.py", line 37, in compute_forward
    a = self.modules.CnnBlock(rf)
  File "/home/arian/anaconda3/envs/StableV4/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/arian/anaconda3/envs/StableV4/lib/python3.10/site-packages/torch/nn/modules/container.py", line 217, in forward
    input = module(input)
  File "/home/arian/anaconda3/envs/StableV4/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/arian/anaconda3/envs/StableV4/lib/python3.10/site-packages/speechbrain/nnet/CNN.py", line 136, in forward
    x = self._manage_padding(
  File "/home/arian/anaconda3/envs/StableV4/lib/python3.10/site-packages/speechbrain/nnet/CNN.py", line 304, in _manage_padding
    x = F.pad(x, padding, mode=self.padding_mode)
RuntimeError: Argument #4: Padding size should be less than the corresponding input dimension, but got: padding (62, 62) at dimension 2 of input [6, 4500, 1]
2023-10-18 16:11:36,211 - speechbrain.core - INFO - Beginning experiment!
2023-10-18 16:11:36,211 - speechbrain.core - INFO - Experiment folder: Results/Ultrasound_sinc
2023-10-18 16:11:36,510 - speechbrain.utils.superpowers - DEBUG - appdirs==1.4.4
audioread==3.0.0
beautifulsoup4==4.12.2
bs4==0.0.1
certifi @ file:///croot/certifi_1690232220950/work/certifi
cffi==1.15.1
charset-normalizer==3.2.0
cloudpickle==2.2.1
cmake==3.27.5
contourpy==1.1.1
cssselect==1.2.0
cycler==0.11.0
Cython==3.0.2
decorator==5.1.1
dnspython==2.4.2
exceptiongroup==1.1.3
fake-useragent==1.2.1
falcon==3.1.1
falcon-cors==1.1.7
filelock==3.12.4
fonttools==4.42.1
fsspec==2023.9.2
gitdb==4.0.10
GitPython==3.1.36
GPy==1.10.0
gunicorn==21.2.0
huggingface-hub==0.17.3
HyperPyYAML==1.2.2
idna==3.4
importlib-metadata==6.8.0
iniconfig==2.0.0
Jinja2==3.1.2
joblib==1.3.2
kaleido==0.2.1
kiwisolver==1.4.5
lazy_loader==0.3
librosa==0.10.1
lit==16.0.6
llvmlite==0.41.0
lxml==4.9.3
MarkupSafe==2.1.3
matplotlib==3.8.0
mpmath==1.3.0
msgpack==1.0.6
networkx==3.1
numba==0.58.0
numpy==1.25.2
nvidia-cublas-cu11==11.10.3.66
nvidia-cuda-cupti-cu11==11.7.101
nvidia-cuda-nvrtc-cu11==11.7.99
nvidia-cuda-runtime-cu11==11.7.99
nvidia-cudnn-cu11==8.5.0.96
nvidia-cufft-cu11==10.9.0.58
nvidia-curand-cu11==10.2.10.91
nvidia-cusolver-cu11==11.4.0.1
nvidia-cusparse-cu11==11.7.4.91
nvidia-nccl-cu11==2.14.3
nvidia-nvtx-cu11==11.7.91
orion==0.2.7
packaging==23.1
pandas==2.1.1
paramz==0.9.5
parse==1.19.1
Pillow==10.0.1
platformdirs==3.10.0
plotly==5.17.0
pluggy==1.3.0
pooch==1.7.0
profet==0.0.1
psutil==5.9.5
pyaml==23.9.6
pycparser==2.21
pyee==8.2.2
pymongo==4.5.0
pyparsing==3.1.1
pypdb==2.3
pyppeteer==1.0.2
pyquery==2.0.0
pytest==7.4.2
python-dateutil==2.8.2
pytz==2023.3.post1
PyYAML==6.0.1
requests==2.31.0
requests-html==0.10.0
ruamel.yaml==0.17.35
ruamel.yaml.clib==0.2.8
scikit-learn==1.3.1
scikit-optimize==0.9.0
scipy==1.11.2
seaborn==0.12.2
sentencepiece==0.1.99
six==1.16.0
smmap==5.0.1
soundfile==0.12.1
soupsieve==2.5
soxr==0.3.6
speechbrain==0.5.15
sympy==1.12
tabulate==0.9.0
tenacity==8.2.3
threadpoolctl==3.2.0
tomli==2.0.1
torch==2.0.1
torchaudio==2.0.2
torchvision==0.15.2
tqdm==4.66.1
triton==2.0.0
typing_extensions==4.8.0
tzdata==2023.3
urllib3==1.26.16
w3lib==2.1.2
websockets==10.4
zipp==3.17.0


2023-10-18 16:11:36,512 - speechbrain.utils.superpowers - DEBUG - 188471c


2023-10-18 16:11:37,574 - speechbrain.core - INFO - 176.2k trainable parameters in Ultra_Brain
2023-10-18 16:11:37,575 - speechbrain.utils.checkpoints - INFO - Would load a checkpoint here, but none found yet.
2023-10-18 16:11:37,575 - speechbrain.utils.epoch_loop - INFO - Going into epoch 1
2023-10-18 16:11:37,587 - speechbrain.core - ERROR - Exception:
Traceback (most recent call last):
  File "/home/arian/PycharmProjects/SpeechBrain_Ultra/./models/train_NeuralNets_sinc.py", line 155, in <module>
    Ultra_brain.fit(
  File "/home/arian/anaconda3/envs/StableV4/lib/python3.10/site-packages/speechbrain/core.py", line 1264, in fit
    self._fit_train(train_set=train_set, epoch=epoch, enable=enable)
  File "/home/arian/anaconda3/envs/StableV4/lib/python3.10/site-packages/speechbrain/core.py", line 1116, in _fit_train
    loss = self.fit_batch(batch)
  File "/home/arian/PycharmProjects/SpeechBrain_Ultra/./models/train_NeuralNets_sinc.py", line 51, in fit_batch
    predictions = self.compute_forward(batch)
  File "/home/arian/PycharmProjects/SpeechBrain_Ultra/./models/train_NeuralNets_sinc.py", line 37, in compute_forward
    a = self.modules.CnnBlock(rf)
  File "/home/arian/anaconda3/envs/StableV4/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/arian/anaconda3/envs/StableV4/lib/python3.10/site-packages/torch/nn/modules/container.py", line 217, in forward
    input = module(input)
  File "/home/arian/anaconda3/envs/StableV4/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/arian/anaconda3/envs/StableV4/lib/python3.10/site-packages/speechbrain/nnet/CNN.py", line 136, in forward
    x = self._manage_padding(
  File "/home/arian/anaconda3/envs/StableV4/lib/python3.10/site-packages/speechbrain/nnet/CNN.py", line 304, in _manage_padding
    x = F.pad(x, padding, mode=self.padding_mode)
RuntimeError: Argument #4: Padding size should be less than the corresponding input dimension, but got: padding (62, 62) at dimension 2 of input [6, 4500, 1]
2023-10-18 16:12:34,831 - speechbrain.core - INFO - Beginning experiment!
2023-10-18 16:12:34,832 - speechbrain.core - INFO - Experiment folder: Results/Ultrasound_sinc
2023-10-18 16:12:35,136 - speechbrain.utils.superpowers - DEBUG - appdirs==1.4.4
audioread==3.0.0
beautifulsoup4==4.12.2
bs4==0.0.1
certifi @ file:///croot/certifi_1690232220950/work/certifi
cffi==1.15.1
charset-normalizer==3.2.0
cloudpickle==2.2.1
cmake==3.27.5
contourpy==1.1.1
cssselect==1.2.0
cycler==0.11.0
Cython==3.0.2
decorator==5.1.1
dnspython==2.4.2
exceptiongroup==1.1.3
fake-useragent==1.2.1
falcon==3.1.1
falcon-cors==1.1.7
filelock==3.12.4
fonttools==4.42.1
fsspec==2023.9.2
gitdb==4.0.10
GitPython==3.1.36
GPy==1.10.0
gunicorn==21.2.0
huggingface-hub==0.17.3
HyperPyYAML==1.2.2
idna==3.4
importlib-metadata==6.8.0
iniconfig==2.0.0
Jinja2==3.1.2
joblib==1.3.2
kaleido==0.2.1
kiwisolver==1.4.5
lazy_loader==0.3
librosa==0.10.1
lit==16.0.6
llvmlite==0.41.0
lxml==4.9.3
MarkupSafe==2.1.3
matplotlib==3.8.0
mpmath==1.3.0
msgpack==1.0.6
networkx==3.1
numba==0.58.0
numpy==1.25.2
nvidia-cublas-cu11==11.10.3.66
nvidia-cuda-cupti-cu11==11.7.101
nvidia-cuda-nvrtc-cu11==11.7.99
nvidia-cuda-runtime-cu11==11.7.99
nvidia-cudnn-cu11==8.5.0.96
nvidia-cufft-cu11==10.9.0.58
nvidia-curand-cu11==10.2.10.91
nvidia-cusolver-cu11==11.4.0.1
nvidia-cusparse-cu11==11.7.4.91
nvidia-nccl-cu11==2.14.3
nvidia-nvtx-cu11==11.7.91
orion==0.2.7
packaging==23.1
pandas==2.1.1
paramz==0.9.5
parse==1.19.1
Pillow==10.0.1
platformdirs==3.10.0
plotly==5.17.0
pluggy==1.3.0
pooch==1.7.0
profet==0.0.1
psutil==5.9.5
pyaml==23.9.6
pycparser==2.21
pyee==8.2.2
pymongo==4.5.0
pyparsing==3.1.1
pypdb==2.3
pyppeteer==1.0.2
pyquery==2.0.0
pytest==7.4.2
python-dateutil==2.8.2
pytz==2023.3.post1
PyYAML==6.0.1
requests==2.31.0
requests-html==0.10.0
ruamel.yaml==0.17.35
ruamel.yaml.clib==0.2.8
scikit-learn==1.3.1
scikit-optimize==0.9.0
scipy==1.11.2
seaborn==0.12.2
sentencepiece==0.1.99
six==1.16.0
smmap==5.0.1
soundfile==0.12.1
soupsieve==2.5
soxr==0.3.6
speechbrain==0.5.15
sympy==1.12
tabulate==0.9.0
tenacity==8.2.3
threadpoolctl==3.2.0
tomli==2.0.1
torch==2.0.1
torchaudio==2.0.2
torchvision==0.15.2
tqdm==4.66.1
triton==2.0.0
typing_extensions==4.8.0
tzdata==2023.3
urllib3==1.26.16
w3lib==2.1.2
websockets==10.4
zipp==3.17.0


2023-10-18 16:12:35,138 - speechbrain.utils.superpowers - DEBUG - 188471c


2023-10-18 16:12:36,196 - speechbrain.core - INFO - 176.2k trainable parameters in Ultra_Brain
2023-10-18 16:12:36,197 - speechbrain.utils.checkpoints - INFO - Would load a checkpoint here, but none found yet.
2023-10-18 16:12:36,197 - speechbrain.utils.epoch_loop - INFO - Going into epoch 1
2023-10-18 16:12:36,884 - speechbrain.core - ERROR - Exception:
Traceback (most recent call last):
  File "/home/arian/PycharmProjects/SpeechBrain_Ultra/./models/train_NeuralNets_sinc.py", line 155, in <module>
    Ultra_brain.fit(
  File "/home/arian/anaconda3/envs/StableV4/lib/python3.10/site-packages/speechbrain/core.py", line 1264, in fit
    self._fit_train(train_set=train_set, epoch=epoch, enable=enable)
  File "/home/arian/anaconda3/envs/StableV4/lib/python3.10/site-packages/speechbrain/core.py", line 1116, in _fit_train
    loss = self.fit_batch(batch)
  File "/home/arian/PycharmProjects/SpeechBrain_Ultra/./models/train_NeuralNets_sinc.py", line 51, in fit_batch
    predictions = self.compute_forward(batch)
  File "/home/arian/PycharmProjects/SpeechBrain_Ultra/./models/train_NeuralNets_sinc.py", line 37, in compute_forward
    a = self.modules.CnnBlock(rf)
  File "/home/arian/anaconda3/envs/StableV4/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/arian/anaconda3/envs/StableV4/lib/python3.10/site-packages/torch/nn/modules/container.py", line 217, in forward
    input = module(input)
  File "/home/arian/anaconda3/envs/StableV4/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/arian/anaconda3/envs/StableV4/lib/python3.10/site-packages/torch/nn/modules/conv.py", line 313, in forward
    return self._conv_forward(input, self.weight, self.bias)
  File "/home/arian/anaconda3/envs/StableV4/lib/python3.10/site-packages/torch/nn/modules/conv.py", line 309, in _conv_forward
    return F.conv1d(input, weight, bias, self.stride,
RuntimeError: Given groups=1, weight of size [128, 256, 4], expected input[6, 2250, 256] to have 256 channels, but got 2250 channels instead
2023-10-18 16:21:21,012 - speechbrain.core - INFO - Beginning experiment!
2023-10-18 16:21:21,012 - speechbrain.core - INFO - Experiment folder: Results/Ultrasound_sinc
2023-10-18 16:21:21,323 - speechbrain.utils.superpowers - DEBUG - appdirs==1.4.4
audioread==3.0.0
beautifulsoup4==4.12.2
bs4==0.0.1
certifi @ file:///croot/certifi_1690232220950/work/certifi
cffi==1.15.1
charset-normalizer==3.2.0
cloudpickle==2.2.1
cmake==3.27.5
contourpy==1.1.1
cssselect==1.2.0
cycler==0.11.0
Cython==3.0.2
decorator==5.1.1
dnspython==2.4.2
exceptiongroup==1.1.3
fake-useragent==1.2.1
falcon==3.1.1
falcon-cors==1.1.7
filelock==3.12.4
fonttools==4.42.1
fsspec==2023.9.2
gitdb==4.0.10
GitPython==3.1.36
GPy==1.10.0
gunicorn==21.2.0
huggingface-hub==0.17.3
HyperPyYAML==1.2.2
idna==3.4
importlib-metadata==6.8.0
iniconfig==2.0.0
Jinja2==3.1.2
joblib==1.3.2
kaleido==0.2.1
kiwisolver==1.4.5
lazy_loader==0.3
librosa==0.10.1
lit==16.0.6
llvmlite==0.41.0
lxml==4.9.3
MarkupSafe==2.1.3
matplotlib==3.8.0
mpmath==1.3.0
msgpack==1.0.6
networkx==3.1
numba==0.58.0
numpy==1.25.2
nvidia-cublas-cu11==11.10.3.66
nvidia-cuda-cupti-cu11==11.7.101
nvidia-cuda-nvrtc-cu11==11.7.99
nvidia-cuda-runtime-cu11==11.7.99
nvidia-cudnn-cu11==8.5.0.96
nvidia-cufft-cu11==10.9.0.58
nvidia-curand-cu11==10.2.10.91
nvidia-cusolver-cu11==11.4.0.1
nvidia-cusparse-cu11==11.7.4.91
nvidia-nccl-cu11==2.14.3
nvidia-nvtx-cu11==11.7.91
orion==0.2.7
packaging==23.1
pandas==2.1.1
paramz==0.9.5
parse==1.19.1
Pillow==10.0.1
platformdirs==3.10.0
plotly==5.17.0
pluggy==1.3.0
pooch==1.7.0
profet==0.0.1
psutil==5.9.5
pyaml==23.9.6
pycparser==2.21
pyee==8.2.2
pymongo==4.5.0
pyparsing==3.1.1
pypdb==2.3
pyppeteer==1.0.2
pyquery==2.0.0
pytest==7.4.2
python-dateutil==2.8.2
pytz==2023.3.post1
PyYAML==6.0.1
requests==2.31.0
requests-html==0.10.0
ruamel.yaml==0.17.35
ruamel.yaml.clib==0.2.8
scikit-learn==1.3.1
scikit-optimize==0.9.0
scipy==1.11.2
seaborn==0.12.2
sentencepiece==0.1.99
six==1.16.0
smmap==5.0.1
soundfile==0.12.1
soupsieve==2.5
soxr==0.3.6
speechbrain==0.5.15
sympy==1.12
tabulate==0.9.0
tenacity==8.2.3
threadpoolctl==3.2.0
tomli==2.0.1
torch==2.0.1
torchaudio==2.0.2
torchvision==0.15.2
tqdm==4.66.1
triton==2.0.0
typing_extensions==4.8.0
tzdata==2023.3
urllib3==1.26.16
w3lib==2.1.2
websockets==10.4
zipp==3.17.0


2023-10-18 16:21:21,325 - speechbrain.utils.superpowers - DEBUG - 188471c


2023-10-18 16:21:22,423 - speechbrain.core - INFO - 176.2k trainable parameters in Ultra_Brain
2023-10-18 16:21:22,423 - speechbrain.utils.checkpoints - INFO - Would load a checkpoint here, but none found yet.
2023-10-18 16:21:22,423 - speechbrain.utils.epoch_loop - INFO - Going into epoch 1
2023-10-18 16:21:22,717 - speechbrain.core - ERROR - Exception:
Traceback (most recent call last):
  File "/home/arian/PycharmProjects/SpeechBrain_Ultra/./models/train_NeuralNets_sinc.py", line 156, in <module>
    Ultra_brain.fit(
  File "/home/arian/anaconda3/envs/StableV4/lib/python3.10/site-packages/speechbrain/core.py", line 1264, in fit
    self._fit_train(train_set=train_set, epoch=epoch, enable=enable)
  File "/home/arian/anaconda3/envs/StableV4/lib/python3.10/site-packages/speechbrain/core.py", line 1116, in _fit_train
    loss = self.fit_batch(batch)
  File "/home/arian/PycharmProjects/SpeechBrain_Ultra/./models/train_NeuralNets_sinc.py", line 52, in fit_batch
    predictions = self.compute_forward(batch)
  File "/home/arian/PycharmProjects/SpeechBrain_Ultra/./models/train_NeuralNets_sinc.py", line 38, in compute_forward
    a = self.modules.CnnBlock(rf)
  File "/home/arian/anaconda3/envs/StableV4/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/arian/anaconda3/envs/StableV4/lib/python3.10/site-packages/torch/nn/modules/container.py", line 217, in forward
    input = module(input)
  File "/home/arian/anaconda3/envs/StableV4/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/arian/anaconda3/envs/StableV4/lib/python3.10/site-packages/speechbrain/nnet/CNN.py", line 153, in forward
    sinc_filters = self._get_sinc_filters()
  File "/home/arian/anaconda3/envs/StableV4/lib/python3.10/site-packages/speechbrain/nnet/CNN.py", line 231, in _get_sinc_filters
    filters = band_pass.view(self.out_channels, 1, self.kernel_size)
RuntimeError: shape '[256, 1, 256]' is invalid for input of size 65792
2023-10-18 16:22:07,308 - speechbrain.core - INFO - Beginning experiment!
2023-10-18 16:22:07,308 - speechbrain.core - INFO - Experiment folder: Results/Ultrasound_sinc
2023-10-18 16:22:07,613 - speechbrain.utils.superpowers - DEBUG - appdirs==1.4.4
audioread==3.0.0
beautifulsoup4==4.12.2
bs4==0.0.1
certifi @ file:///croot/certifi_1690232220950/work/certifi
cffi==1.15.1
charset-normalizer==3.2.0
cloudpickle==2.2.1
cmake==3.27.5
contourpy==1.1.1
cssselect==1.2.0
cycler==0.11.0
Cython==3.0.2
decorator==5.1.1
dnspython==2.4.2
exceptiongroup==1.1.3
fake-useragent==1.2.1
falcon==3.1.1
falcon-cors==1.1.7
filelock==3.12.4
fonttools==4.42.1
fsspec==2023.9.2
gitdb==4.0.10
GitPython==3.1.36
GPy==1.10.0
gunicorn==21.2.0
huggingface-hub==0.17.3
HyperPyYAML==1.2.2
idna==3.4
importlib-metadata==6.8.0
iniconfig==2.0.0
Jinja2==3.1.2
joblib==1.3.2
kaleido==0.2.1
kiwisolver==1.4.5
lazy_loader==0.3
librosa==0.10.1
lit==16.0.6
llvmlite==0.41.0
lxml==4.9.3
MarkupSafe==2.1.3
matplotlib==3.8.0
mpmath==1.3.0
msgpack==1.0.6
networkx==3.1
numba==0.58.0
numpy==1.25.2
nvidia-cublas-cu11==11.10.3.66
nvidia-cuda-cupti-cu11==11.7.101
nvidia-cuda-nvrtc-cu11==11.7.99
nvidia-cuda-runtime-cu11==11.7.99
nvidia-cudnn-cu11==8.5.0.96
nvidia-cufft-cu11==10.9.0.58
nvidia-curand-cu11==10.2.10.91
nvidia-cusolver-cu11==11.4.0.1
nvidia-cusparse-cu11==11.7.4.91
nvidia-nccl-cu11==2.14.3
nvidia-nvtx-cu11==11.7.91
orion==0.2.7
packaging==23.1
pandas==2.1.1
paramz==0.9.5
parse==1.19.1
Pillow==10.0.1
platformdirs==3.10.0
plotly==5.17.0
pluggy==1.3.0
pooch==1.7.0
profet==0.0.1
psutil==5.9.5
pyaml==23.9.6
pycparser==2.21
pyee==8.2.2
pymongo==4.5.0
pyparsing==3.1.1
pypdb==2.3
pyppeteer==1.0.2
pyquery==2.0.0
pytest==7.4.2
python-dateutil==2.8.2
pytz==2023.3.post1
PyYAML==6.0.1
requests==2.31.0
requests-html==0.10.0
ruamel.yaml==0.17.35
ruamel.yaml.clib==0.2.8
scikit-learn==1.3.1
scikit-optimize==0.9.0
scipy==1.11.2
seaborn==0.12.2
sentencepiece==0.1.99
six==1.16.0
smmap==5.0.1
soundfile==0.12.1
soupsieve==2.5
soxr==0.3.6
speechbrain==0.5.15
sympy==1.12
tabulate==0.9.0
tenacity==8.2.3
threadpoolctl==3.2.0
tomli==2.0.1
torch==2.0.1
torchaudio==2.0.2
torchvision==0.15.2
tqdm==4.66.1
triton==2.0.0
typing_extensions==4.8.0
tzdata==2023.3
urllib3==1.26.16
w3lib==2.1.2
websockets==10.4
zipp==3.17.0


2023-10-18 16:22:07,615 - speechbrain.utils.superpowers - DEBUG - 188471c


2023-10-18 16:22:08,671 - speechbrain.core - INFO - 176.2k trainable parameters in Ultra_Brain
2023-10-18 16:22:08,671 - speechbrain.utils.checkpoints - INFO - Would load a checkpoint here, but none found yet.
2023-10-18 16:22:08,671 - speechbrain.utils.epoch_loop - INFO - Going into epoch 1
2023-10-18 16:22:08,963 - speechbrain.core - ERROR - Exception:
Traceback (most recent call last):
  File "/home/arian/PycharmProjects/SpeechBrain_Ultra/./models/train_NeuralNets_sinc.py", line 156, in <module>
    Ultra_brain.fit(
  File "/home/arian/anaconda3/envs/StableV4/lib/python3.10/site-packages/speechbrain/core.py", line 1264, in fit
    self._fit_train(train_set=train_set, epoch=epoch, enable=enable)
  File "/home/arian/anaconda3/envs/StableV4/lib/python3.10/site-packages/speechbrain/core.py", line 1116, in _fit_train
    loss = self.fit_batch(batch)
  File "/home/arian/PycharmProjects/SpeechBrain_Ultra/./models/train_NeuralNets_sinc.py", line 52, in fit_batch
    predictions = self.compute_forward(batch)
  File "/home/arian/PycharmProjects/SpeechBrain_Ultra/./models/train_NeuralNets_sinc.py", line 38, in compute_forward
    a = self.modules.CnnBlock(rf)
  File "/home/arian/anaconda3/envs/StableV4/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/arian/anaconda3/envs/StableV4/lib/python3.10/site-packages/torch/nn/modules/container.py", line 217, in forward
    input = module(input)
  File "/home/arian/anaconda3/envs/StableV4/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/arian/anaconda3/envs/StableV4/lib/python3.10/site-packages/speechbrain/nnet/CNN.py", line 153, in forward
    sinc_filters = self._get_sinc_filters()
  File "/home/arian/anaconda3/envs/StableV4/lib/python3.10/site-packages/speechbrain/nnet/CNN.py", line 231, in _get_sinc_filters
    filters = band_pass.view(self.out_channels, 1, self.kernel_size)
RuntimeError: shape '[256, 1, 256]' is invalid for input of size 65792
2023-10-18 16:23:23,176 - speechbrain.core - INFO - Beginning experiment!
2023-10-18 16:23:23,176 - speechbrain.core - INFO - Experiment folder: Results/Ultrasound_sinc
2023-10-18 16:23:23,475 - speechbrain.utils.superpowers - DEBUG - appdirs==1.4.4
audioread==3.0.0
beautifulsoup4==4.12.2
bs4==0.0.1
certifi @ file:///croot/certifi_1690232220950/work/certifi
cffi==1.15.1
charset-normalizer==3.2.0
cloudpickle==2.2.1
cmake==3.27.5
contourpy==1.1.1
cssselect==1.2.0
cycler==0.11.0
Cython==3.0.2
decorator==5.1.1
dnspython==2.4.2
exceptiongroup==1.1.3
fake-useragent==1.2.1
falcon==3.1.1
falcon-cors==1.1.7
filelock==3.12.4
fonttools==4.42.1
fsspec==2023.9.2
gitdb==4.0.10
GitPython==3.1.36
GPy==1.10.0
gunicorn==21.2.0
huggingface-hub==0.17.3
HyperPyYAML==1.2.2
idna==3.4
importlib-metadata==6.8.0
iniconfig==2.0.0
Jinja2==3.1.2
joblib==1.3.2
kaleido==0.2.1
kiwisolver==1.4.5
lazy_loader==0.3
librosa==0.10.1
lit==16.0.6
llvmlite==0.41.0
lxml==4.9.3
MarkupSafe==2.1.3
matplotlib==3.8.0
mpmath==1.3.0
msgpack==1.0.6
networkx==3.1
numba==0.58.0
numpy==1.25.2
nvidia-cublas-cu11==11.10.3.66
nvidia-cuda-cupti-cu11==11.7.101
nvidia-cuda-nvrtc-cu11==11.7.99
nvidia-cuda-runtime-cu11==11.7.99
nvidia-cudnn-cu11==8.5.0.96
nvidia-cufft-cu11==10.9.0.58
nvidia-curand-cu11==10.2.10.91
nvidia-cusolver-cu11==11.4.0.1
nvidia-cusparse-cu11==11.7.4.91
nvidia-nccl-cu11==2.14.3
nvidia-nvtx-cu11==11.7.91
orion==0.2.7
packaging==23.1
pandas==2.1.1
paramz==0.9.5
parse==1.19.1
Pillow==10.0.1
platformdirs==3.10.0
plotly==5.17.0
pluggy==1.3.0
pooch==1.7.0
profet==0.0.1
psutil==5.9.5
pyaml==23.9.6
pycparser==2.21
pyee==8.2.2
pymongo==4.5.0
pyparsing==3.1.1
pypdb==2.3
pyppeteer==1.0.2
pyquery==2.0.0
pytest==7.4.2
python-dateutil==2.8.2
pytz==2023.3.post1
PyYAML==6.0.1
requests==2.31.0
requests-html==0.10.0
ruamel.yaml==0.17.35
ruamel.yaml.clib==0.2.8
scikit-learn==1.3.1
scikit-optimize==0.9.0
scipy==1.11.2
seaborn==0.12.2
sentencepiece==0.1.99
six==1.16.0
smmap==5.0.1
soundfile==0.12.1
soupsieve==2.5
soxr==0.3.6
speechbrain==0.5.15
sympy==1.12
tabulate==0.9.0
tenacity==8.2.3
threadpoolctl==3.2.0
tomli==2.0.1
torch==2.0.1
torchaudio==2.0.2
torchvision==0.15.2
tqdm==4.66.1
triton==2.0.0
typing_extensions==4.8.0
tzdata==2023.3
urllib3==1.26.16
w3lib==2.1.2
websockets==10.4
zipp==3.17.0


2023-10-18 16:23:23,477 - speechbrain.utils.superpowers - DEBUG - 188471c


2023-10-18 16:23:24,538 - speechbrain.core - INFO - 176.2k trainable parameters in Ultra_Brain
2023-10-18 16:23:24,539 - speechbrain.utils.checkpoints - INFO - Would load a checkpoint here, but none found yet.
2023-10-18 16:23:24,539 - speechbrain.utils.epoch_loop - INFO - Going into epoch 1
2023-10-18 16:23:24,550 - speechbrain.core - ERROR - Exception:
Traceback (most recent call last):
  File "/home/arian/PycharmProjects/SpeechBrain_Ultra/./models/train_NeuralNets_sinc.py", line 156, in <module>
    Ultra_brain.fit(
  File "/home/arian/anaconda3/envs/StableV4/lib/python3.10/site-packages/speechbrain/core.py", line 1264, in fit
    self._fit_train(train_set=train_set, epoch=epoch, enable=enable)
  File "/home/arian/anaconda3/envs/StableV4/lib/python3.10/site-packages/speechbrain/core.py", line 1116, in _fit_train
    loss = self.fit_batch(batch)
  File "/home/arian/PycharmProjects/SpeechBrain_Ultra/./models/train_NeuralNets_sinc.py", line 52, in fit_batch
    predictions = self.compute_forward(batch)
  File "/home/arian/PycharmProjects/SpeechBrain_Ultra/./models/train_NeuralNets_sinc.py", line 38, in compute_forward
    a = self.modules.CnnBlock(rf)
  File "/home/arian/anaconda3/envs/StableV4/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/arian/anaconda3/envs/StableV4/lib/python3.10/site-packages/torch/nn/modules/container.py", line 217, in forward
    input = module(input)
  File "/home/arian/anaconda3/envs/StableV4/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/arian/anaconda3/envs/StableV4/lib/python3.10/site-packages/speechbrain/nnet/CNN.py", line 136, in forward
    x = self._manage_padding(
  File "/home/arian/anaconda3/envs/StableV4/lib/python3.10/site-packages/speechbrain/nnet/CNN.py", line 304, in _manage_padding
    x = F.pad(x, padding, mode=self.padding_mode)
RuntimeError: Argument #4: Padding size should be less than the corresponding input dimension, but got: padding (128, 128) at dimension 2 of input [6, 4500, 1]
2023-10-18 16:24:01,948 - speechbrain.core - INFO - Beginning experiment!
2023-10-18 16:24:01,948 - speechbrain.core - INFO - Experiment folder: Results/Ultrasound_sinc
2023-10-18 16:24:02,254 - speechbrain.utils.superpowers - DEBUG - appdirs==1.4.4
audioread==3.0.0
beautifulsoup4==4.12.2
bs4==0.0.1
certifi @ file:///croot/certifi_1690232220950/work/certifi
cffi==1.15.1
charset-normalizer==3.2.0
cloudpickle==2.2.1
cmake==3.27.5
contourpy==1.1.1
cssselect==1.2.0
cycler==0.11.0
Cython==3.0.2
decorator==5.1.1
dnspython==2.4.2
exceptiongroup==1.1.3
fake-useragent==1.2.1
falcon==3.1.1
falcon-cors==1.1.7
filelock==3.12.4
fonttools==4.42.1
fsspec==2023.9.2
gitdb==4.0.10
GitPython==3.1.36
GPy==1.10.0
gunicorn==21.2.0
huggingface-hub==0.17.3
HyperPyYAML==1.2.2
idna==3.4
importlib-metadata==6.8.0
iniconfig==2.0.0
Jinja2==3.1.2
joblib==1.3.2
kaleido==0.2.1
kiwisolver==1.4.5
lazy_loader==0.3
librosa==0.10.1
lit==16.0.6
llvmlite==0.41.0
lxml==4.9.3
MarkupSafe==2.1.3
matplotlib==3.8.0
mpmath==1.3.0
msgpack==1.0.6
networkx==3.1
numba==0.58.0
numpy==1.25.2
nvidia-cublas-cu11==11.10.3.66
nvidia-cuda-cupti-cu11==11.7.101
nvidia-cuda-nvrtc-cu11==11.7.99
nvidia-cuda-runtime-cu11==11.7.99
nvidia-cudnn-cu11==8.5.0.96
nvidia-cufft-cu11==10.9.0.58
nvidia-curand-cu11==10.2.10.91
nvidia-cusolver-cu11==11.4.0.1
nvidia-cusparse-cu11==11.7.4.91
nvidia-nccl-cu11==2.14.3
nvidia-nvtx-cu11==11.7.91
orion==0.2.7
packaging==23.1
pandas==2.1.1
paramz==0.9.5
parse==1.19.1
Pillow==10.0.1
platformdirs==3.10.0
plotly==5.17.0
pluggy==1.3.0
pooch==1.7.0
profet==0.0.1
psutil==5.9.5
pyaml==23.9.6
pycparser==2.21
pyee==8.2.2
pymongo==4.5.0
pyparsing==3.1.1
pypdb==2.3
pyppeteer==1.0.2
pyquery==2.0.0
pytest==7.4.2
python-dateutil==2.8.2
pytz==2023.3.post1
PyYAML==6.0.1
requests==2.31.0
requests-html==0.10.0
ruamel.yaml==0.17.35
ruamel.yaml.clib==0.2.8
scikit-learn==1.3.1
scikit-optimize==0.9.0
scipy==1.11.2
seaborn==0.12.2
sentencepiece==0.1.99
six==1.16.0
smmap==5.0.1
soundfile==0.12.1
soupsieve==2.5
soxr==0.3.6
speechbrain==0.5.15
sympy==1.12
tabulate==0.9.0
tenacity==8.2.3
threadpoolctl==3.2.0
tomli==2.0.1
torch==2.0.1
torchaudio==2.0.2
torchvision==0.15.2
tqdm==4.66.1
triton==2.0.0
typing_extensions==4.8.0
tzdata==2023.3
urllib3==1.26.16
w3lib==2.1.2
websockets==10.4
zipp==3.17.0


2023-10-18 16:24:02,255 - speechbrain.utils.superpowers - DEBUG - 188471c


2023-10-18 16:24:03,349 - speechbrain.core - INFO - 176.2k trainable parameters in Ultra_Brain
2023-10-18 16:24:03,349 - speechbrain.utils.checkpoints - INFO - Would load a checkpoint here, but none found yet.
2023-10-18 16:24:03,349 - speechbrain.utils.epoch_loop - INFO - Going into epoch 1
2023-10-18 16:24:03,640 - speechbrain.core - ERROR - Exception:
Traceback (most recent call last):
  File "/home/arian/PycharmProjects/SpeechBrain_Ultra/./models/train_NeuralNets_sinc.py", line 156, in <module>
    Ultra_brain.fit(
  File "/home/arian/anaconda3/envs/StableV4/lib/python3.10/site-packages/speechbrain/core.py", line 1264, in fit
    self._fit_train(train_set=train_set, epoch=epoch, enable=enable)
  File "/home/arian/anaconda3/envs/StableV4/lib/python3.10/site-packages/speechbrain/core.py", line 1116, in _fit_train
    loss = self.fit_batch(batch)
  File "/home/arian/PycharmProjects/SpeechBrain_Ultra/./models/train_NeuralNets_sinc.py", line 52, in fit_batch
    predictions = self.compute_forward(batch)
  File "/home/arian/PycharmProjects/SpeechBrain_Ultra/./models/train_NeuralNets_sinc.py", line 38, in compute_forward
    a = self.modules.CnnBlock(rf)
  File "/home/arian/anaconda3/envs/StableV4/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/arian/anaconda3/envs/StableV4/lib/python3.10/site-packages/torch/nn/modules/container.py", line 217, in forward
    input = module(input)
  File "/home/arian/anaconda3/envs/StableV4/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/arian/anaconda3/envs/StableV4/lib/python3.10/site-packages/speechbrain/nnet/CNN.py", line 153, in forward
    sinc_filters = self._get_sinc_filters()
  File "/home/arian/anaconda3/envs/StableV4/lib/python3.10/site-packages/speechbrain/nnet/CNN.py", line 231, in _get_sinc_filters
    filters = band_pass.view(self.out_channels, 1, self.kernel_size)
RuntimeError: shape '[256, 1, 256]' is invalid for input of size 65792
2023-10-18 16:26:44,921 - speechbrain.core - INFO - Beginning experiment!
2023-10-18 16:26:44,922 - speechbrain.core - INFO - Experiment folder: Results/Ultrasound_sinc
2023-10-18 16:26:45,227 - speechbrain.utils.superpowers - DEBUG - appdirs==1.4.4
audioread==3.0.0
beautifulsoup4==4.12.2
bs4==0.0.1
certifi @ file:///croot/certifi_1690232220950/work/certifi
cffi==1.15.1
charset-normalizer==3.2.0
cloudpickle==2.2.1
cmake==3.27.5
contourpy==1.1.1
cssselect==1.2.0
cycler==0.11.0
Cython==3.0.2
decorator==5.1.1
dnspython==2.4.2
exceptiongroup==1.1.3
fake-useragent==1.2.1
falcon==3.1.1
falcon-cors==1.1.7
filelock==3.12.4
fonttools==4.42.1
fsspec==2023.9.2
gitdb==4.0.10
GitPython==3.1.36
GPy==1.10.0
gunicorn==21.2.0
huggingface-hub==0.17.3
HyperPyYAML==1.2.2
idna==3.4
importlib-metadata==6.8.0
iniconfig==2.0.0
Jinja2==3.1.2
joblib==1.3.2
kaleido==0.2.1
kiwisolver==1.4.5
lazy_loader==0.3
librosa==0.10.1
lit==16.0.6
llvmlite==0.41.0
lxml==4.9.3
MarkupSafe==2.1.3
matplotlib==3.8.0
mpmath==1.3.0
msgpack==1.0.6
networkx==3.1
numba==0.58.0
numpy==1.25.2
nvidia-cublas-cu11==11.10.3.66
nvidia-cuda-cupti-cu11==11.7.101
nvidia-cuda-nvrtc-cu11==11.7.99
nvidia-cuda-runtime-cu11==11.7.99
nvidia-cudnn-cu11==8.5.0.96
nvidia-cufft-cu11==10.9.0.58
nvidia-curand-cu11==10.2.10.91
nvidia-cusolver-cu11==11.4.0.1
nvidia-cusparse-cu11==11.7.4.91
nvidia-nccl-cu11==2.14.3
nvidia-nvtx-cu11==11.7.91
orion==0.2.7
packaging==23.1
pandas==2.1.1
paramz==0.9.5
parse==1.19.1
Pillow==10.0.1
platformdirs==3.10.0
plotly==5.17.0
pluggy==1.3.0
pooch==1.7.0
profet==0.0.1
psutil==5.9.5
pyaml==23.9.6
pycparser==2.21
pyee==8.2.2
pymongo==4.5.0
pyparsing==3.1.1
pypdb==2.3
pyppeteer==1.0.2
pyquery==2.0.0
pytest==7.4.2
python-dateutil==2.8.2
pytz==2023.3.post1
PyYAML==6.0.1
requests==2.31.0
requests-html==0.10.0
ruamel.yaml==0.17.35
ruamel.yaml.clib==0.2.8
scikit-learn==1.3.1
scikit-optimize==0.9.0
scipy==1.11.2
seaborn==0.12.2
sentencepiece==0.1.99
six==1.16.0
smmap==5.0.1
soundfile==0.12.1
soupsieve==2.5
soxr==0.3.6
speechbrain==0.5.15
sympy==1.12
tabulate==0.9.0
tenacity==8.2.3
threadpoolctl==3.2.0
tomli==2.0.1
torch==2.0.1
torchaudio==2.0.2
torchvision==0.15.2
tqdm==4.66.1
triton==2.0.0
typing_extensions==4.8.0
tzdata==2023.3
urllib3==1.26.16
w3lib==2.1.2
websockets==10.4
zipp==3.17.0


2023-10-18 16:26:45,229 - speechbrain.utils.superpowers - DEBUG - 188471c


2023-10-18 16:26:46,305 - speechbrain.core - INFO - 175.7k trainable parameters in Ultra_Brain
2023-10-18 16:26:46,305 - speechbrain.utils.checkpoints - INFO - Would load a checkpoint here, but none found yet.
2023-10-18 16:26:46,305 - speechbrain.utils.epoch_loop - INFO - Going into epoch 1
2023-10-18 16:26:46,311 - speechbrain.core - ERROR - Exception:
Traceback (most recent call last):
  File "/home/arian/PycharmProjects/SpeechBrain_Ultra/./models/train_NeuralNets_sinc.py", line 158, in <module>
    Ultra_brain.fit(
  File "/home/arian/anaconda3/envs/StableV4/lib/python3.10/site-packages/speechbrain/core.py", line 1264, in fit
    self._fit_train(train_set=train_set, epoch=epoch, enable=enable)
  File "/home/arian/anaconda3/envs/StableV4/lib/python3.10/site-packages/speechbrain/core.py", line 1116, in _fit_train
    loss = self.fit_batch(batch)
  File "/home/arian/PycharmProjects/SpeechBrain_Ultra/./models/train_NeuralNets_sinc.py", line 54, in fit_batch
    predictions = self.compute_forward(batch)
  File "/home/arian/PycharmProjects/SpeechBrain_Ultra/./models/train_NeuralNets_sinc.py", line 38, in compute_forward
    a = self.modules.SincBlock(rf)
  File "/home/arian/anaconda3/envs/StableV4/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1614, in __getattr__
    raise AttributeError("'{}' object has no attribute '{}'".format(
AttributeError: 'ModuleDict' object has no attribute 'SincBlock'
2023-10-18 16:28:13,450 - speechbrain.core - INFO - Beginning experiment!
2023-10-18 16:28:13,450 - speechbrain.core - INFO - Experiment folder: Results/Ultrasound_sinc
2023-10-18 16:28:13,750 - speechbrain.utils.superpowers - DEBUG - appdirs==1.4.4
audioread==3.0.0
beautifulsoup4==4.12.2
bs4==0.0.1
certifi @ file:///croot/certifi_1690232220950/work/certifi
cffi==1.15.1
charset-normalizer==3.2.0
cloudpickle==2.2.1
cmake==3.27.5
contourpy==1.1.1
cssselect==1.2.0
cycler==0.11.0
Cython==3.0.2
decorator==5.1.1
dnspython==2.4.2
exceptiongroup==1.1.3
fake-useragent==1.2.1
falcon==3.1.1
falcon-cors==1.1.7
filelock==3.12.4
fonttools==4.42.1
fsspec==2023.9.2
gitdb==4.0.10
GitPython==3.1.36
GPy==1.10.0
gunicorn==21.2.0
huggingface-hub==0.17.3
HyperPyYAML==1.2.2
idna==3.4
importlib-metadata==6.8.0
iniconfig==2.0.0
Jinja2==3.1.2
joblib==1.3.2
kaleido==0.2.1
kiwisolver==1.4.5
lazy_loader==0.3
librosa==0.10.1
lit==16.0.6
llvmlite==0.41.0
lxml==4.9.3
MarkupSafe==2.1.3
matplotlib==3.8.0
mpmath==1.3.0
msgpack==1.0.6
networkx==3.1
numba==0.58.0
numpy==1.25.2
nvidia-cublas-cu11==11.10.3.66
nvidia-cuda-cupti-cu11==11.7.101
nvidia-cuda-nvrtc-cu11==11.7.99
nvidia-cuda-runtime-cu11==11.7.99
nvidia-cudnn-cu11==8.5.0.96
nvidia-cufft-cu11==10.9.0.58
nvidia-curand-cu11==10.2.10.91
nvidia-cusolver-cu11==11.4.0.1
nvidia-cusparse-cu11==11.7.4.91
nvidia-nccl-cu11==2.14.3
nvidia-nvtx-cu11==11.7.91
orion==0.2.7
packaging==23.1
pandas==2.1.1
paramz==0.9.5
parse==1.19.1
Pillow==10.0.1
platformdirs==3.10.0
plotly==5.17.0
pluggy==1.3.0
pooch==1.7.0
profet==0.0.1
psutil==5.9.5
pyaml==23.9.6
pycparser==2.21
pyee==8.2.2
pymongo==4.5.0
pyparsing==3.1.1
pypdb==2.3
pyppeteer==1.0.2
pyquery==2.0.0
pytest==7.4.2
python-dateutil==2.8.2
pytz==2023.3.post1
PyYAML==6.0.1
requests==2.31.0
requests-html==0.10.0
ruamel.yaml==0.17.35
ruamel.yaml.clib==0.2.8
scikit-learn==1.3.1
scikit-optimize==0.9.0
scipy==1.11.2
seaborn==0.12.2
sentencepiece==0.1.99
six==1.16.0
smmap==5.0.1
soundfile==0.12.1
soupsieve==2.5
soxr==0.3.6
speechbrain==0.5.15
sympy==1.12
tabulate==0.9.0
tenacity==8.2.3
threadpoolctl==3.2.0
tomli==2.0.1
torch==2.0.1
torchaudio==2.0.2
torchvision==0.15.2
tqdm==4.66.1
triton==2.0.0
typing_extensions==4.8.0
tzdata==2023.3
urllib3==1.26.16
w3lib==2.1.2
websockets==10.4
zipp==3.17.0


2023-10-18 16:28:13,752 - speechbrain.utils.superpowers - DEBUG - 188471c


2023-10-18 16:28:14,816 - speechbrain.core - INFO - 175.7k trainable parameters in Ultra_Brain
2023-10-18 16:28:14,817 - speechbrain.utils.checkpoints - INFO - Would load a checkpoint here, but none found yet.
2023-10-18 16:28:14,817 - speechbrain.utils.epoch_loop - INFO - Going into epoch 1
2023-10-18 16:28:14,822 - speechbrain.core - ERROR - Exception:
Traceback (most recent call last):
  File "/home/arian/PycharmProjects/SpeechBrain_Ultra/./models/train_NeuralNets_sinc.py", line 158, in <module>
    Ultra_brain.fit(
  File "/home/arian/anaconda3/envs/StableV4/lib/python3.10/site-packages/speechbrain/core.py", line 1264, in fit
    self._fit_train(train_set=train_set, epoch=epoch, enable=enable)
  File "/home/arian/anaconda3/envs/StableV4/lib/python3.10/site-packages/speechbrain/core.py", line 1116, in _fit_train
    loss = self.fit_batch(batch)
  File "/home/arian/PycharmProjects/SpeechBrain_Ultra/./models/train_NeuralNets_sinc.py", line 54, in fit_batch
    predictions = self.compute_forward(batch)
  File "/home/arian/PycharmProjects/SpeechBrain_Ultra/./models/train_NeuralNets_sinc.py", line 38, in compute_forward
    a = self.modules.SincBlock(rf)
  File "/home/arian/anaconda3/envs/StableV4/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1614, in __getattr__
    raise AttributeError("'{}' object has no attribute '{}'".format(
AttributeError: 'ModuleDict' object has no attribute 'SincBlock'
2023-10-18 16:28:52,784 - speechbrain.core - INFO - Beginning experiment!
2023-10-18 16:28:52,784 - speechbrain.core - INFO - Experiment folder: Results/Ultrasound_sinc
2023-10-18 16:28:53,091 - speechbrain.utils.superpowers - DEBUG - appdirs==1.4.4
audioread==3.0.0
beautifulsoup4==4.12.2
bs4==0.0.1
certifi @ file:///croot/certifi_1690232220950/work/certifi
cffi==1.15.1
charset-normalizer==3.2.0
cloudpickle==2.2.1
cmake==3.27.5
contourpy==1.1.1
cssselect==1.2.0
cycler==0.11.0
Cython==3.0.2
decorator==5.1.1
dnspython==2.4.2
exceptiongroup==1.1.3
fake-useragent==1.2.1
falcon==3.1.1
falcon-cors==1.1.7
filelock==3.12.4
fonttools==4.42.1
fsspec==2023.9.2
gitdb==4.0.10
GitPython==3.1.36
GPy==1.10.0
gunicorn==21.2.0
huggingface-hub==0.17.3
HyperPyYAML==1.2.2
idna==3.4
importlib-metadata==6.8.0
iniconfig==2.0.0
Jinja2==3.1.2
joblib==1.3.2
kaleido==0.2.1
kiwisolver==1.4.5
lazy_loader==0.3
librosa==0.10.1
lit==16.0.6
llvmlite==0.41.0
lxml==4.9.3
MarkupSafe==2.1.3
matplotlib==3.8.0
mpmath==1.3.0
msgpack==1.0.6
networkx==3.1
numba==0.58.0
numpy==1.25.2
nvidia-cublas-cu11==11.10.3.66
nvidia-cuda-cupti-cu11==11.7.101
nvidia-cuda-nvrtc-cu11==11.7.99
nvidia-cuda-runtime-cu11==11.7.99
nvidia-cudnn-cu11==8.5.0.96
nvidia-cufft-cu11==10.9.0.58
nvidia-curand-cu11==10.2.10.91
nvidia-cusolver-cu11==11.4.0.1
nvidia-cusparse-cu11==11.7.4.91
nvidia-nccl-cu11==2.14.3
nvidia-nvtx-cu11==11.7.91
orion==0.2.7
packaging==23.1
pandas==2.1.1
paramz==0.9.5
parse==1.19.1
Pillow==10.0.1
platformdirs==3.10.0
plotly==5.17.0
pluggy==1.3.0
pooch==1.7.0
profet==0.0.1
psutil==5.9.5
pyaml==23.9.6
pycparser==2.21
pyee==8.2.2
pymongo==4.5.0
pyparsing==3.1.1
pypdb==2.3
pyppeteer==1.0.2
pyquery==2.0.0
pytest==7.4.2
python-dateutil==2.8.2
pytz==2023.3.post1
PyYAML==6.0.1
requests==2.31.0
requests-html==0.10.0
ruamel.yaml==0.17.35
ruamel.yaml.clib==0.2.8
scikit-learn==1.3.1
scikit-optimize==0.9.0
scipy==1.11.2
seaborn==0.12.2
sentencepiece==0.1.99
six==1.16.0
smmap==5.0.1
soundfile==0.12.1
soupsieve==2.5
soxr==0.3.6
speechbrain==0.5.15
sympy==1.12
tabulate==0.9.0
tenacity==8.2.3
threadpoolctl==3.2.0
tomli==2.0.1
torch==2.0.1
torchaudio==2.0.2
torchvision==0.15.2
tqdm==4.66.1
triton==2.0.0
typing_extensions==4.8.0
tzdata==2023.3
urllib3==1.26.16
w3lib==2.1.2
websockets==10.4
zipp==3.17.0


2023-10-18 16:28:53,093 - speechbrain.utils.superpowers - DEBUG - 188471c


2023-10-18 16:28:54,207 - speechbrain.core - INFO - 176.2k trainable parameters in Ultra_Brain
2023-10-18 16:28:54,207 - speechbrain.utils.checkpoints - INFO - Would load a checkpoint here, but none found yet.
2023-10-18 16:28:54,207 - speechbrain.utils.epoch_loop - INFO - Going into epoch 1
2023-10-18 16:28:54,511 - speechbrain.core - ERROR - Exception:
Traceback (most recent call last):
  File "/home/arian/PycharmProjects/SpeechBrain_Ultra/./models/train_NeuralNets_sinc.py", line 158, in <module>
    Ultra_brain.fit(
  File "/home/arian/anaconda3/envs/StableV4/lib/python3.10/site-packages/speechbrain/core.py", line 1264, in fit
    self._fit_train(train_set=train_set, epoch=epoch, enable=enable)
  File "/home/arian/anaconda3/envs/StableV4/lib/python3.10/site-packages/speechbrain/core.py", line 1116, in _fit_train
    loss = self.fit_batch(batch)
  File "/home/arian/PycharmProjects/SpeechBrain_Ultra/./models/train_NeuralNets_sinc.py", line 54, in fit_batch
    predictions = self.compute_forward(batch)
  File "/home/arian/PycharmProjects/SpeechBrain_Ultra/./models/train_NeuralNets_sinc.py", line 38, in compute_forward
    a = self.modules.SincBlock(rf)
  File "/home/arian/anaconda3/envs/StableV4/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/arian/anaconda3/envs/StableV4/lib/python3.10/site-packages/torch/nn/modules/container.py", line 217, in forward
    input = module(input)
  File "/home/arian/anaconda3/envs/StableV4/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/arian/anaconda3/envs/StableV4/lib/python3.10/site-packages/speechbrain/nnet/CNN.py", line 153, in forward
    sinc_filters = self._get_sinc_filters()
  File "/home/arian/anaconda3/envs/StableV4/lib/python3.10/site-packages/speechbrain/nnet/CNN.py", line 231, in _get_sinc_filters
    filters = band_pass.view(self.out_channels, 1, self.kernel_size)
RuntimeError: shape '[256, 1, 256]' is invalid for input of size 65792
2023-10-18 16:30:09,903 - speechbrain.core - INFO - Beginning experiment!
2023-10-18 16:30:09,903 - speechbrain.core - INFO - Experiment folder: Results/Ultrasound_sinc
2023-10-18 16:30:10,207 - speechbrain.utils.superpowers - DEBUG - appdirs==1.4.4
audioread==3.0.0
beautifulsoup4==4.12.2
bs4==0.0.1
certifi @ file:///croot/certifi_1690232220950/work/certifi
cffi==1.15.1
charset-normalizer==3.2.0
cloudpickle==2.2.1
cmake==3.27.5
contourpy==1.1.1
cssselect==1.2.0
cycler==0.11.0
Cython==3.0.2
decorator==5.1.1
dnspython==2.4.2
exceptiongroup==1.1.3
fake-useragent==1.2.1
falcon==3.1.1
falcon-cors==1.1.7
filelock==3.12.4
fonttools==4.42.1
fsspec==2023.9.2
gitdb==4.0.10
GitPython==3.1.36
GPy==1.10.0
gunicorn==21.2.0
huggingface-hub==0.17.3
HyperPyYAML==1.2.2
idna==3.4
importlib-metadata==6.8.0
iniconfig==2.0.0
Jinja2==3.1.2
joblib==1.3.2
kaleido==0.2.1
kiwisolver==1.4.5
lazy_loader==0.3
librosa==0.10.1
lit==16.0.6
llvmlite==0.41.0
lxml==4.9.3
MarkupSafe==2.1.3
matplotlib==3.8.0
mpmath==1.3.0
msgpack==1.0.6
networkx==3.1
numba==0.58.0
numpy==1.25.2
nvidia-cublas-cu11==11.10.3.66
nvidia-cuda-cupti-cu11==11.7.101
nvidia-cuda-nvrtc-cu11==11.7.99
nvidia-cuda-runtime-cu11==11.7.99
nvidia-cudnn-cu11==8.5.0.96
nvidia-cufft-cu11==10.9.0.58
nvidia-curand-cu11==10.2.10.91
nvidia-cusolver-cu11==11.4.0.1
nvidia-cusparse-cu11==11.7.4.91
nvidia-nccl-cu11==2.14.3
nvidia-nvtx-cu11==11.7.91
orion==0.2.7
packaging==23.1
pandas==2.1.1
paramz==0.9.5
parse==1.19.1
Pillow==10.0.1
platformdirs==3.10.0
plotly==5.17.0
pluggy==1.3.0
pooch==1.7.0
profet==0.0.1
psutil==5.9.5
pyaml==23.9.6
pycparser==2.21
pyee==8.2.2
pymongo==4.5.0
pyparsing==3.1.1
pypdb==2.3
pyppeteer==1.0.2
pyquery==2.0.0
pytest==7.4.2
python-dateutil==2.8.2
pytz==2023.3.post1
PyYAML==6.0.1
requests==2.31.0
requests-html==0.10.0
ruamel.yaml==0.17.35
ruamel.yaml.clib==0.2.8
scikit-learn==1.3.1
scikit-optimize==0.9.0
scipy==1.11.2
seaborn==0.12.2
sentencepiece==0.1.99
six==1.16.0
smmap==5.0.1
soundfile==0.12.1
soupsieve==2.5
soxr==0.3.6
speechbrain==0.5.15
sympy==1.12
tabulate==0.9.0
tenacity==8.2.3
threadpoolctl==3.2.0
tomli==2.0.1
torch==2.0.1
torchaudio==2.0.2
torchvision==0.15.2
tqdm==4.66.1
triton==2.0.0
typing_extensions==4.8.0
tzdata==2023.3
urllib3==1.26.16
w3lib==2.1.2
websockets==10.4
zipp==3.17.0


2023-10-18 16:30:10,209 - speechbrain.utils.superpowers - DEBUG - 188471c


2023-10-18 16:30:11,293 - speechbrain.core - INFO - 176.2k trainable parameters in Ultra_Brain
2023-10-18 16:30:11,293 - speechbrain.utils.checkpoints - INFO - Would load a checkpoint here, but none found yet.
2023-10-18 16:30:11,293 - speechbrain.utils.epoch_loop - INFO - Going into epoch 1
2023-10-18 16:30:11,978 - speechbrain.core - ERROR - Exception:
Traceback (most recent call last):
  File "/home/arian/PycharmProjects/SpeechBrain_Ultra/./models/train_NeuralNets_sinc.py", line 158, in <module>
    Ultra_brain.fit(
  File "/home/arian/anaconda3/envs/StableV4/lib/python3.10/site-packages/speechbrain/core.py", line 1264, in fit
    self._fit_train(train_set=train_set, epoch=epoch, enable=enable)
  File "/home/arian/anaconda3/envs/StableV4/lib/python3.10/site-packages/speechbrain/core.py", line 1116, in _fit_train
    loss = self.fit_batch(batch)
  File "/home/arian/PycharmProjects/SpeechBrain_Ultra/./models/train_NeuralNets_sinc.py", line 54, in fit_batch
    predictions = self.compute_forward(batch)
  File "/home/arian/PycharmProjects/SpeechBrain_Ultra/./models/train_NeuralNets_sinc.py", line 40, in compute_forward
    a = self.modules.CnnBlock(a)
  File "/home/arian/anaconda3/envs/StableV4/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/arian/anaconda3/envs/StableV4/lib/python3.10/site-packages/torch/nn/modules/container.py", line 217, in forward
    input = module(input)
  File "/home/arian/anaconda3/envs/StableV4/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/arian/anaconda3/envs/StableV4/lib/python3.10/site-packages/torch/nn/modules/conv.py", line 313, in forward
    return self._conv_forward(input, self.weight, self.bias)
  File "/home/arian/anaconda3/envs/StableV4/lib/python3.10/site-packages/torch/nn/modules/conv.py", line 309, in _conv_forward
    return F.conv1d(input, weight, bias, self.stride,
RuntimeError: Given groups=1, weight of size [128, 256, 4], expected input[6, 2250, 256] to have 256 channels, but got 2250 channels instead
2023-10-18 16:32:34,826 - speechbrain.core - INFO - Beginning experiment!
2023-10-18 16:32:34,827 - speechbrain.core - INFO - Experiment folder: Results/Ultrasound_sinc
2023-10-18 16:32:35,127 - speechbrain.utils.superpowers - DEBUG - appdirs==1.4.4
audioread==3.0.0
beautifulsoup4==4.12.2
bs4==0.0.1
certifi @ file:///croot/certifi_1690232220950/work/certifi
cffi==1.15.1
charset-normalizer==3.2.0
cloudpickle==2.2.1
cmake==3.27.5
contourpy==1.1.1
cssselect==1.2.0
cycler==0.11.0
Cython==3.0.2
decorator==5.1.1
dnspython==2.4.2
exceptiongroup==1.1.3
fake-useragent==1.2.1
falcon==3.1.1
falcon-cors==1.1.7
filelock==3.12.4
fonttools==4.42.1
fsspec==2023.9.2
gitdb==4.0.10
GitPython==3.1.36
GPy==1.10.0
gunicorn==21.2.0
huggingface-hub==0.17.3
HyperPyYAML==1.2.2
idna==3.4
importlib-metadata==6.8.0
iniconfig==2.0.0
Jinja2==3.1.2
joblib==1.3.2
kaleido==0.2.1
kiwisolver==1.4.5
lazy_loader==0.3
librosa==0.10.1
lit==16.0.6
llvmlite==0.41.0
lxml==4.9.3
MarkupSafe==2.1.3
matplotlib==3.8.0
mpmath==1.3.0
msgpack==1.0.6
networkx==3.1
numba==0.58.0
numpy==1.25.2
nvidia-cublas-cu11==11.10.3.66
nvidia-cuda-cupti-cu11==11.7.101
nvidia-cuda-nvrtc-cu11==11.7.99
nvidia-cuda-runtime-cu11==11.7.99
nvidia-cudnn-cu11==8.5.0.96
nvidia-cufft-cu11==10.9.0.58
nvidia-curand-cu11==10.2.10.91
nvidia-cusolver-cu11==11.4.0.1
nvidia-cusparse-cu11==11.7.4.91
nvidia-nccl-cu11==2.14.3
nvidia-nvtx-cu11==11.7.91
orion==0.2.7
packaging==23.1
pandas==2.1.1
paramz==0.9.5
parse==1.19.1
Pillow==10.0.1
platformdirs==3.10.0
plotly==5.17.0
pluggy==1.3.0
pooch==1.7.0
profet==0.0.1
psutil==5.9.5
pyaml==23.9.6
pycparser==2.21
pyee==8.2.2
pymongo==4.5.0
pyparsing==3.1.1
pypdb==2.3
pyppeteer==1.0.2
pyquery==2.0.0
pytest==7.4.2
python-dateutil==2.8.2
pytz==2023.3.post1
PyYAML==6.0.1
requests==2.31.0
requests-html==0.10.0
ruamel.yaml==0.17.35
ruamel.yaml.clib==0.2.8
scikit-learn==1.3.1
scikit-optimize==0.9.0
scipy==1.11.2
seaborn==0.12.2
sentencepiece==0.1.99
six==1.16.0
smmap==5.0.1
soundfile==0.12.1
soupsieve==2.5
soxr==0.3.6
speechbrain==0.5.15
sympy==1.12
tabulate==0.9.0
tenacity==8.2.3
threadpoolctl==3.2.0
tomli==2.0.1
torch==2.0.1
torchaudio==2.0.2
torchvision==0.15.2
tqdm==4.66.1
triton==2.0.0
typing_extensions==4.8.0
tzdata==2023.3
urllib3==1.26.16
w3lib==2.1.2
websockets==10.4
zipp==3.17.0


2023-10-18 16:32:35,129 - speechbrain.utils.superpowers - DEBUG - 188471c


2023-10-18 16:32:36,188 - speechbrain.core - INFO - 176.2k trainable parameters in Ultra_Brain
2023-10-18 16:32:36,189 - speechbrain.utils.checkpoints - INFO - Would load a checkpoint here, but none found yet.
2023-10-18 16:32:36,189 - speechbrain.utils.epoch_loop - INFO - Going into epoch 1
2023-10-18 16:32:39,841 - speechbrain.core - ERROR - Exception:
Traceback (most recent call last):
  File "/home/arian/PycharmProjects/SpeechBrain_Ultra/./models/train_NeuralNets_sinc.py", line 159, in <module>
    Ultra_brain.fit(
  File "/home/arian/anaconda3/envs/StableV4/lib/python3.10/site-packages/speechbrain/core.py", line 1264, in fit
    self._fit_train(train_set=train_set, epoch=epoch, enable=enable)
  File "/home/arian/anaconda3/envs/StableV4/lib/python3.10/site-packages/speechbrain/core.py", line 1116, in _fit_train
    loss = self.fit_batch(batch)
  File "/home/arian/PycharmProjects/SpeechBrain_Ultra/./models/train_NeuralNets_sinc.py", line 60, in fit_batch
    if self.check_gradients(loss):
  File "/home/arian/anaconda3/envs/StableV4/lib/python3.10/site-packages/speechbrain/core.py", line 1032, in check_gradients
    if not torch.isfinite(loss):
KeyboardInterrupt
2023-10-18 16:42:44,058 - speechbrain.core - INFO - Beginning experiment!
2023-10-18 16:42:44,059 - speechbrain.core - INFO - Experiment folder: Results/Ultrasound_sinc
2023-10-18 16:42:44,357 - speechbrain.utils.superpowers - DEBUG - appdirs==1.4.4
audioread==3.0.0
beautifulsoup4==4.12.2
bs4==0.0.1
certifi @ file:///croot/certifi_1690232220950/work/certifi
cffi==1.15.1
charset-normalizer==3.2.0
cloudpickle==2.2.1
cmake==3.27.5
contourpy==1.1.1
cssselect==1.2.0
cycler==0.11.0
Cython==3.0.2
decorator==5.1.1
dnspython==2.4.2
exceptiongroup==1.1.3
fake-useragent==1.2.1
falcon==3.1.1
falcon-cors==1.1.7
filelock==3.12.4
fonttools==4.42.1
fsspec==2023.9.2
gitdb==4.0.10
GitPython==3.1.36
GPy==1.10.0
gunicorn==21.2.0
huggingface-hub==0.17.3
HyperPyYAML==1.2.2
idna==3.4
importlib-metadata==6.8.0
iniconfig==2.0.0
Jinja2==3.1.2
joblib==1.3.2
kaleido==0.2.1
kiwisolver==1.4.5
lazy_loader==0.3
librosa==0.10.1
lit==16.0.6
llvmlite==0.41.0
lxml==4.9.3
MarkupSafe==2.1.3
matplotlib==3.8.0
mpmath==1.3.0
msgpack==1.0.6
networkx==3.1
numba==0.58.0
numpy==1.25.2
nvidia-cublas-cu11==11.10.3.66
nvidia-cuda-cupti-cu11==11.7.101
nvidia-cuda-nvrtc-cu11==11.7.99
nvidia-cuda-runtime-cu11==11.7.99
nvidia-cudnn-cu11==8.5.0.96
nvidia-cufft-cu11==10.9.0.58
nvidia-curand-cu11==10.2.10.91
nvidia-cusolver-cu11==11.4.0.1
nvidia-cusparse-cu11==11.7.4.91
nvidia-nccl-cu11==2.14.3
nvidia-nvtx-cu11==11.7.91
orion==0.2.7
packaging==23.1
pandas==2.1.1
paramz==0.9.5
parse==1.19.1
Pillow==10.0.1
platformdirs==3.10.0
plotly==5.17.0
pluggy==1.3.0
pooch==1.7.0
profet==0.0.1
psutil==5.9.5
pyaml==23.9.6
pycparser==2.21
pyee==8.2.2
pymongo==4.5.0
pyparsing==3.1.1
pypdb==2.3
pyppeteer==1.0.2
pyquery==2.0.0
pytest==7.4.2
python-dateutil==2.8.2
pytz==2023.3.post1
PyYAML==6.0.1
requests==2.31.0
requests-html==0.10.0
ruamel.yaml==0.17.35
ruamel.yaml.clib==0.2.8
scikit-learn==1.3.1
scikit-optimize==0.9.0
scipy==1.11.2
seaborn==0.12.2
sentencepiece==0.1.99
six==1.16.0
smmap==5.0.1
soundfile==0.12.1
soupsieve==2.5
soxr==0.3.6
speechbrain==0.5.15
sympy==1.12
tabulate==0.9.0
tenacity==8.2.3
threadpoolctl==3.2.0
tomli==2.0.1
torch==2.0.1
torchaudio==2.0.2
torchvision==0.15.2
tqdm==4.66.1
triton==2.0.0
typing_extensions==4.8.0
tzdata==2023.3
urllib3==1.26.16
w3lib==2.1.2
websockets==10.4
zipp==3.17.0


2023-10-18 16:42:44,359 - speechbrain.utils.superpowers - DEBUG - 188471c


2023-10-18 16:42:45,414 - speechbrain.core - INFO - 176.2k trainable parameters in Ultra_Brain
2023-10-18 16:42:45,414 - speechbrain.utils.checkpoints - INFO - Would load a checkpoint here, but none found yet.
2023-10-18 16:42:45,414 - speechbrain.utils.epoch_loop - INFO - Going into epoch 1
2023-10-18 16:42:53,711 - speechbrain.core - ERROR - Exception:
Traceback (most recent call last):
  File "/home/arian/PycharmProjects/SpeechBrain_Ultra/./models/train_NeuralNets_sinc.py", line 154, in <module>
    Ultra_brain.fit(
  File "/home/arian/anaconda3/envs/StableV4/lib/python3.10/site-packages/speechbrain/core.py", line 1264, in fit
    self._fit_train(train_set=train_set, epoch=epoch, enable=enable)
  File "/home/arian/anaconda3/envs/StableV4/lib/python3.10/site-packages/speechbrain/core.py", line 1116, in _fit_train
    loss = self.fit_batch(batch)
  File "/home/arian/PycharmProjects/SpeechBrain_Ultra/./models/train_NeuralNets_sinc.py", line 55, in fit_batch
    if self.check_gradients(loss):
  File "/home/arian/anaconda3/envs/StableV4/lib/python3.10/site-packages/speechbrain/core.py", line 1056, in check_gradients
    torch.nn.utils.clip_grad_norm_(
  File "/home/arian/anaconda3/envs/StableV4/lib/python3.10/site-packages/torch/nn/utils/clip_grad.py", line 61, in clip_grad_norm_
    total_norm = torch.norm(torch.stack([norm.to(first_device) for norm in norms]), norm_type)
KeyboardInterrupt
